#ifndef _APPS_UNACE_EXE_COMMLINE_HELP_H_INCLUDED
#define _APPS_UNACE_EXE_COMMLINE_HELP_H_INCLUDED


#define APPS_UNACE_EXE_COMMLINE_HELP_COPYRIGHTLINES 2

void    APPS_UNACE_EXE_COMMLINE_HELP_PrintHelp(BOOL DoPrintCopyRight);
void    APPS_UNACE_EXE_COMMLINE_HELP_CreateFirstHelpLine(void);


#endif
