#ifndef _BASE_CPRDCPR_LZ77_H_INCLUDED
#define _BASE_CPRDCPR_LZ77_H_INCLUDED

//------ConstantDefines:

#define BASE_CPRDCPR_LZ77_MAXCODEWIDTH       11
#define BASE_CPRDCPR_LZ77_MAXLEN             259
#define BASE_CPRDCPR_LZ77_MAXDISTATLEN2      255
#define BASE_CPRDCPR_LZ77_MAXDISTATLEN3      8191

#define BASE_CPRDCPR_LZ77_MAXDICBITS         22
#define BASE_CPRDCPR_LZ77_MAXDICBITS2        (BASE_CPRDCPR_LZ77_MAXDICBITS >> 1)
#define BASE_CPRDCPR_LZ77_MAXDICSIZE         (1 << BASE_CPRDCPR_LZ77_MAXDICBITS)
#define BASE_CPRDCPR_LZ77_MAXDIST2           (1 << BASE_CPRDCPR_LZ77_MAXDICBITS2)

#define BASE_CPRDCPR_LZ77_DEFBLOCKSIZE       8500
#define BASE_CPRDCPR_LZ77_MAXBLOCKSIZE       9500
#define BASE_CPRDCPR_LZ77_MAXMAINCODE        (260 + BASE_CPRDCPR_LZ77_MAXDICBITS + 2)
#define BASE_CPRDCPR_LZ77_MAXLENCODE         (256 - 1)
#define BASE_CPRDCPR_LZ77_TYPECODE           (260 + BASE_CPRDCPR_LZ77_MAXDICBITS + 1)
#define BASE_CPRDCPR_LZ77_NUMDICSIZES        (BASE_CPRDCPR_LZ77_MAXDICBITS - 15 + 1)

#define BASE_CPRDCPR_LZ77_MAXDELTABLOCK      65536


#endif
