#ifndef _BASE_VERSION_H_INCLUDED
#define _BASE_VERSION_H_INCLUDED

#define BASE_VERSION_VERSIONSTR "2.5  "
#define BASE_VERSION_VERSIONNUM 20

#define BASE_VERSION_ISBETA     0
#define BASE_VERSION_BETAYEAR   101
#define BASE_VERSION_BETADAY    30
#define BASE_VERSION_BETAENDSTR "2nd january 2002"

#endif
